[platformio]
; Domyślne środowisko (podstawowa wersja)
default_envs = basic_default

; ==========================================================
; WSPÓLNA KONFIGURACJA DLA WSZYSTKICH
; ==========================================================
[env]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
; Opcje kompilatora - wymuszamy C++17 i wyłączamy pewne ostrzeżenia
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -D CORE_DEBUG_LEVEL=3
monitor_filters = direct, esp32_exception_decoder

; ==========================================================
; 0. WERSJA PODSTAWOWA (Domyślna)
; ==========================================================
[env:basic_default]
build_flags = 
    ${env.build_flags}
    -D MODULE_DEFAULT

; ==========================================================
; 1. SYSTEM DOSTĘPU (Zamek, RFID, Klawiatura)
; ==========================================================
[env:access_system]
build_flags = 
    ${env.build_flags}
    -D MODULE_ACCESS

; ==========================================================
; 2. SYSTEM ŚRODOWISKOWY (Pogoda, Zasilanie)
; ==========================================================
[env:environment_system]
build_flags = 
    ${env.build_flags}
    -D MODULE_ENV

; ==========================================================
; 3. SYSTEM ALARMOWY (PIR, Gaz, Ogień)
; ==========================================================
[env:security_system]
build_flags = 
    ${env.build_flags}
    -D MODULE_SECURITY